Add I18n support for English
Code4PuertoRico/suministrospr pull request #122
Opened 2020-01-19 14:22 UTC by arielo

Added i18n support for local string to help with translating the site.

- Add i18n with language support for English
- Add a global dropdown language switch to the site footer

Related to Code4PuertoRico/suministrospr/issues/55

@jpadilla Are `.mo` files be compiled as part of the deploy process?

2020-01-19 17:29 UTC, froi commented
This is freaking awesome. Thanks!!!

2020-01-19 22:18 UTC, jpadilla commented
@arielo yeah ideally we can compile those automatically and ignore them from the repo. I think I'd prefer setting up the heroku app to build and run off our Dockerfile instead of fiddling with heroku buildpacks.

I'll start that in a separate PR and let you know.

2020-01-20 00:02 UTC, jpadilla commented on Dockerfile
> +RUN apt-get install -y gettext
I'd suggest tweaking this to improve layer caching:

```
RUN apt-get update && apt-get install -y \
    gettext \
 && rm -rf /var/lib/apt/lists/*
```

2020-01-20 22:32 UTC, jpadilla commented
@arielo https://github.com/Code4PuertoRico/suministrospr/pull/133 is now merged. We can switch the stack officially when merging this PR.

Should be able to do `python manage.py compilemessages` here https://github.com/Code4PuertoRico/suministrospr/pull/133/files#diff-86234f17466797048d187a83f8cc04eaR7

2020-01-21 02:23 UTC, arielo commented
@jpadilla I rebased and updated the PR. Is anyone willing to translate what is missing?

2020-01-29 05:45 UTC, sociovirology commented
> @jpadilla I rebased and updated the PR. Is anyone willing to translate what is missing?

I am willing, but I don't have experience with Django. I've been reading and I think with a little direction I can do it. To start, should I fork https://github.com/arielo/suministrospr/ or https://github.com/Code4PuertoRico/suministrospr?

2020-02-10 17:49 UTC, gcollazo commented
@arielo Status?

2020-02-13 18:56 UTC, arielo commented
@gcollazo Sorry I hadn't seen this. I needed some help translating/reviewing the main text blocks. it looks it's pretty outdated by now so I'll have to rebase. Maybe I can just duplicate the text in line and we can finish the translation separately and avoid further template conflicts.

2020-02-15 15:55 UTC, arielo commented
@gcollazo @sociovirology I rebased this and translated most. Only the main copy needs to be translated here: 
https://github.com/Code4PuertoRico/suministrospr/blob/4912e4df9b0a3153d4c2addc495d11c9c566deb5/suministrospr/suministros/templates/suministros/suministro_list.html#L19

2020-02-17 23:25 UTC, froi commented
@gcollazo What's the status of this PR?

Does it need more work or help?

2020-02-18 00:04 UTC, froi requested changes
@arielo Te deje un code suggestion. Una vez eso se applique creo que esto esta good to go.

2020-02-18 00:04 UTC, froi commented on suministrospr/suministros/templates/suministros/suministro_list.html
> +      La donación de suministros a las áreas más afectadas del país por el terremoto ha sido un éxito. Esta plataforma, administrada por los mismos donantes y recipientes, busca ser un vehículo de di
Here's one option for this translation

```suggestion
      The donation of supplies to the areas affected by the Puerto Rico earthquakes has been a success. This platform, that is administrated by the same donors and recipients, tries to be a fair distribution method for these supplies. This way, supplies arrive where they are most needed.
```

2020-02-19 02:14 UTC, arielo commented
@froi ok it's all yours.

2020-02-19 02:29 UTC, froi approved these changes
Creo que esto esta bien para darle merge. Gracias @arielo 

CC: @gcollazo

2020-03-01 04:14 UTC, merged