Resolves #120 contributing file
Code4PuertoRico/suministrospr pull request #126
Opened 2020-01-19 18:23 UTC by Xiomara7

Para tener algo por dónde empezar, lo vamos modificando. 

Resolves #120

2020-01-19 18:43 UTC, gcollazo approved these changes

2020-01-19 21:19 UTC, froi requested changes
Freaking amazing. Gracias @Xiomara7 ❤️ 

Antes de aprovar esto, @gcollazo que debemos de poner en `Personas Contacto` y `Otros Recursos`? Crees que debemos de poner `TBD` en esas secciones?

2020-01-19 22:41 UTC, gcollazo commented
@froi contactos serían los mismos del footer actual, en otros recursos no sabría que poner.

2020-01-20 00:05 UTC, Xiomara7 commented
Añadí los mismos contactos que están en el footer y removí `otros recursos`.

2020-01-20 00:56 UTC, gcollazo approved these changes

2020-01-20 01:26 UTC, merged